<?php

return [
    'services' => [
        'http://ping.blogs.yandex.ru',
        'http://blogsearch.google.com/ping/RPC2',
        'http://api.my.yahoo.com/RPC2',
        'http://api.my.yahoo.com/rss/ping',
        'http://ping.feedburner.com',
        'http://ping.weblogs.se/',
        'http://rpc.pingomatic.com/',
        'http://bing.com/webmaster/ping.aspx',
        'http://ping.blo.gs/',
        'http://news2paper.com/ping',
        'http://api.moreover.com/RPC2',
        'http://bulkfeeds.net/rpc',
        'http://ipings.com',
        'http://ping.amagle.com/',
        'http://ping.bloggers.jp/rpc/',
        'http://ping.exblog.jp/xmlrpc',
        'http://bblog.com/ping.php',
        'http://bitacoras.net/ping',
        'http://blogdb.jp/xmlrpc',
        'http://blogmatcher.com/u.php',
        'http://coreblog.org/ping/',
        'http://www.lasermemory.com/lsrpc/',
        'http://ping.rootblog.com/rpc.php',
        'http://pingoat.com/goat/RPC2',
        'http://topicexchange.com/RPC2',
        'http://trackback.bakeinu.jp/bakeping.php',
        'http://www.bitacoles.net/ping.php',
        'http://www.blogoole.com/ping/',
        'http://www.blogpeople.net/servlet/weblogUpdates',
        'http://www.mod-pubsub.org/kn_apps/blogchatter/ping.php',
        'http://www.newsisfree.com/RPCCloud',
        'http://www.snipsnap.org/RPC2',
    ],
];
